services:
  frontend:
    build: .
    env_file:
      - .env
      - .env.prod
    container_name: client
    ports:
      - '3020:3020'
    networks: [qucore_auth_network]

networks:
  qucore_auth_network:
    external: true
